Pull request commit (Review)
SabaAlex/FLCD pull request #1
Opened 2020-10-14 15:44 UTC by SabaAlex

2020-10-14 16:01 UTC, Gloria0105 requested changes

2020-10-14 16:01 UTC, Gloria0105 commented on Lab 1b/Lexic.txt
> +            char := letter|digit
You only have = at EBNF not ::=

2020-10-14 16:01 UTC, Gloria0105 commented on Lab 1b/Lexic.txt
> +            char := letter|digit
and you can't make the difference bettween a character and a constant check what you declared:)

2020-10-14 16:13 UTC, merged

2020-10-15 14:14 UTC, dianatalpos commented on Lab 1b/Lexic.txt
>          operators: + - * / % = < <= = => is AND OR !is
"is" should be a reserved word maybe. Or maybe to use some operator